## Getting Started Images

- Read images
- Check images attributes
- Matrix representation
- Color images, spliting and merging channels
- Displaying images using matplotlib
- Saving images

### Import Libraries Required


In [2]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image

# Display images inline:
%matplotlib inline

#### Display images

In [3]:
Image(filename='./img/checkerboard_18x18.png')

In [4]:
# Read image in gray scale
cb_image = cv.imread('./img/checkerboard_84x84.jpg', 0)

# Display pixel value of the image
# Each pixel has 8bits -> 0 - 255
print(cb_image) 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
cb_image[cb_image == 0] = 55

In [6]:
cv.imshow("image", cb_image)
cv.waitKey(1)

-1