## Getting Started Images

- Read images
- Check images attributes
- Matrix representation
- Color images, spliting and merging channels
- Displaying images using matplotlib
- Saving images

### Import Libraries Required


In [7]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image

# Display images inline:
%matplotlib inline

#### Display images

In [13]:
Image(filename='./img/checkerboard_18x18.png')

In [16]:
# Read image in gray scale
cb_image = cv2.imread('./img/checkerboard_18x18.png', 0)

# Display pixel value of the image
# Each pixel has 8bits -> 0 - 255
print(cb_image) 

[[  0   0   0   0   0   0 255 255 255 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255 255 255 255   0   0   0   0   0   0]
 [255 255 255 255 255 255   0   0   0   0   0   0 255 255 255 255 255 255]
 [255 255 255 255 255 255   0   0   0   0   0   0 255 255 255 255 255 255]
 [255 255 255 255 255 255   0   0   0   0   0   0 255 255 255 255 255 255]
 [255 255 255 255 255 255   0   0   0   0   0   0 255 255 255 255 255 255]
 [255 255 255 255 255 255   0   0   0   0   0   0 255 255 255 255 255 255]
 [255 255 255 255 255 255   0   0   0   0   0   0 255 255 255 255 255 255]
 [  0   0   0   0   0   0 255 255 255 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0

In [19]:
Image(cb_image)